## NumPyの配列を作る

In [ ]:
import numpy as np

### array() でNumPyの配列を作る

In [ ]:
a = np.array([0, 1, 2])
print(type(a))
print(a)
print(a.dtype)

<class 'numpy.ndarray'>
[0 1 2]
int64


In [ ]:
b = np.array([1, 1.5, 2])
print(b)
print(b.dtype)

c = np.array([True, False, True, False, False])
print(c)
print(c.dtype)

d = np.array(list("TechAcademy"))
print(d)
print(d.dtype)

[1.  1.5 2. ]
float64
[ True False  True False False]
bool
['T' 'e' 'c' 'h' 'A' 'c' 'a' 'd' 'e' 'm' 'y']
<U1


### 小さい数値を使いたい場合

In [ ]:
e = np.array([100, 200, 300], dtype = np.int16)
print(e)
print(e.dtype)

[100 200 300]
int16


### すでに存在するndarrayのデータ型を変換する

In [ ]:
f = np.array([1.5, 2.5, 3.5])
print(f)
print(f.dtype)

[1.5 2.5 3.5]
float64


In [ ]:
f = f.astype(np.int64)
print(f)
print(f.dtype)

[1 2 3]
int64


### 配列の作成に関する便利なメソッド

#### np.arange()

`range()`のように連続する整数値でndarrayを作りたい場合は`np.arange()`メソッドを使います。引数の指定方法は`range()`と一緒です。引数が1つ（`np.arange(n)`）なら「0以上n未満」、引数が2つ（`np.arange(a, b)`）なら「a以上b未満」、引数が3つ（`np.arange(x, y, z)`）なら「x以上y未満（増分：z）」です。

In [ ]:
a = np.arange(20)
print(a)

b = np.arange(1, 21)
print(b)

c = np.arange(2, 41, 2)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


#### np.linspace()

In [ ]:
d = np.linspace(0, 10, 5)
print(d)

[ 0.   2.5  5.   7.5 10. ]


#### np.empty()

In [ ]:
e = np.empty(5)
print(e)

[ 0.   2.5  5.   7.5 10. ]


#### np.zeros()とnp.ones()

In [ ]:
f = np.zeros(5)
print(f)

[0. 0. 0. 0. 0.]


In [ ]:
f1 = np.ones(5)
print(f1)

[1. 1. 1. 1. 1.]


#### np.random.rand()

In [ ]:
g = np.random.rand(5)
print(g)

[0.7228636  0.82040875 0.60523667 0.3365     0.37044674]


In [ ]:
g = g * 6 + 1
g = g.astype(np.int8)
print(g)

[5 5 4 3 3]


#### np.concatenate()

In [ ]:
h = np.arange(1, 4)    # [1, 2, 3]
i = np.arange(4, 7)    # [4, 5, 6]
j = np.concatenate([h, i])
print(j)

[1 2 3 4 5 6]


#### 補足：tolist()

In [ ]:
gl = g.tolist()
print(gl)

[5, 5, 4, 3, 3]


### 多次元配列を作る

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
a = np.empty((2, 3), dtype=np.int64)

a[0] = [1, 2, 3]
a[1] = [4, 5, 6]

print(a)

[[1 2 3]
 [4 5 6]]


#### 1次元配列を多次元配列に変換するreshape()

In [ ]:
a = np.arange(1, 21)
print(a)
print(a.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)


In [ ]:
b = a.reshape(4, 5)
print(b)
print(b.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(4, 5)


In [ ]:
b3 = a.reshape(2, 2, 5)
print(b3)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


#### 多次元配列を1次元配列に変換するflatten()とravel()

In [ ]:
c = np.arange(1, 21).reshape(4, 5)
d = c.flatten()
print(c)
print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
e = c.ravel()

print(c)
print(e)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


## 配列を使う

### 要素の参照と更新

In [ ]:
a = np.arange(1, 101).reshape(10, 10)
print(a[0, 0])            # 0番目のみ

1


In [ ]:
print(a[1, 1])            # 1番目のみ

12


In [ ]:
print(a[1:3, 1:3])        # 1番目から2番目まで

[[12 13]
 [22 23]]


In [ ]:
print(a[1:5:3, 1:5:3])    # 1番目から4番目まで（増分3で）

[[12 15]
 [42 45]]


In [ ]:
print(a[:5, :5])          # 先頭から4番目まで

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]]


In [ ]:
print(a[7:, 7:])          # 7番目から末尾まで

[[ 78  79  80]
 [ 88  89  90]
 [ 98  99 100]]


In [ ]:
print(a[::3, ::3])        # 先頭から末尾まで（増分3で）

[[  1   4   7  10]
 [ 31  34  37  40]
 [ 61  64  67  70]
 [ 91  94  97 100]]


In [ ]:
print(a[:, :])            # 全体（先頭から末尾まで）」

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


### 要素の新規追加

In [ ]:
a = np.arange(1, 20)                # 1から19までで配列を作成
a = np.append(a, 20)                # 20を追加
a = np.append(a, (21, 22, 23, 24))  # 21から24までを追加
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [ ]:
b = np.arange(1, 6)           # 1から5までで配列を作成
b = np.insert(b, 1, 6)        # 1番目に6を追加
b = np.insert(b, 3, (7, 8))   # 3番目に7と8を追加
print(b)

[1 6 2 7 8 3 4 5]


### 要素の削除

In [ ]:
a = np.arange(5)      # [0 1 2 3 4] の配列を作成
a = np.delete(a, 2)   # 2番目を削除
print(a)

[0 1 3 4]


多次元配列の場合は、引数が1つ増えます。3つ目の引数に0を入れると1行丸々、1の場合は1列丸々削除されます。

In [ ]:
# 1行目を削除
b = np.arange(1, 26).reshape(5, 5)
b = np.delete(b, 1, 0)
print(b)

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
# 1列目を削除
c = np.arange(1, 26).reshape(5, 5)
c = np.delete(c, 1, 1)
print(c)

[[ 1  3  4  5]
 [ 6  8  9 10]
 [11 13 14 15]
 [16 18 19 20]
 [21 23 24 25]]


## NumPyの応用的な使い方

### 四則演算

In [ ]:
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(a + 1)

[ 2  3  4  5  6  7  8  9 10 11]


In [ ]:
print(a - 1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(a * 2)

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
print(a / 2)

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [ ]:
print(a % 2)

[1 0 1 0 1 0 1 0 1 0]


In [ ]:
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)
print(b + a)

[[ 8 10 12]
 [14 16 18]]


In [ ]:
print(b - a)

[[6 6 6]
 [6 6 6]]


もちろん、かけ算とわり算も可能です。

In [ ]:
c = np.arange(1, 5).reshape(2, 2)
d = np.arange(5, 9).reshape(2, 2)
print(c * d)

[[ 5 12]
 [21 32]]


In [ ]:
print(c / d)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


### ユニバーサル関数

In [ ]:
a = np.random.rand(5)
a = a * 6 + 1

print(a)

[3.4259884  3.11343505 1.378662   3.91319536 5.81790553]


In [ ]:
print(np.array(np.floor(a), dtype=np.int64))

[3 3 1 3 5]


In [ ]:
print(np.array(np.ceil(a), dtype=np.int64))

[4 4 2 4 6]


In [ ]:
print(np.array(np.round(a), dtype=np.int64))

[3 3 1 4 6]


### axis（軸）

#### axisの利用例1：np.sum()

In [ ]:
a = np.arange(0, 9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 全要素の合計
print(np.sum(a))

36


In [ ]:
# 縦方向の合計
print(np.sum(a, axis=0))

[ 9 12 15]


In [ ]:
# 横方向の合計
print(np.sum(a, axis=1))

[ 3 12 21]


#### axisの利用例2：np.insert()

In [ ]:
a = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
b = np.array([1, 1, 1])

# 配列aの縦と横の要素数を取得
# （このように書くことで変数hには縦の要素数3、変数vには横の要素数3が格納される）
(h, v) = a.shape

print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
# 上から2番目にbを追加
c = np.insert(a, 2, b, axis=0)
print(c)

[[0 0 0]
 [0 0 0]
 [1 1 1]
 [0 0 0]]


In [ ]:
# 一番下にbを追加
d = np.insert(a, h, b, axis=0)
print(d)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]]


In [ ]:
# 左から2番目にbを追加
e = np.insert(a, 2, b, axis=1)
print(e)

[[0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]]


In [ ]:
# 一番右にbを追加
f = np.insert(a, v, b, axis=1)
print(f)

[[0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]]


#### axisの利用例3：np.delete()

In [ ]:
a = np.arange(1, 26).reshape(5, 5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
b = a.copy()

# 上から1番目を削除
b = np.delete(b, 1, axis=0)
print(b)

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
c = a.copy()

# 左から1番目を削除
c = np.delete(c, 1, 1)
print(c)

[[ 1  3  4  5]
 [ 6  8  9 10]
 [11 13 14 15]
 [16 18 19 20]
 [21 23 24 25]]
